name   名字: Sync Docker Images to ACR

on:   :
  workflow_dispatch:

jobs:   工作:
  sync:   同步:
    runs-on: ubuntu-latest   运行于：ubuntu-latest
    steps:   步骤:
      - name: Login to ACR   - 名称：登录 ACR
        uses: docker/login-action@v3使用：docker/login-action@v3
        with:   :
          registry: crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com注册表：crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}用户名：${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}密码：${{ secrets.ACR_PASSWORD }}

      - name: Pull and push bitnami/postgresql- 名称：拉取和推送 bitnami/postgresql
        run: |   运行:|
          docker pull bitnami/postgresql:latest从 Docker Hub 拉取最新版本的 Bitnami PostgreSQL 镜像。
          docker tag bitnami/postgresql:latest crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com/gitlab/postgresql:latest将镜像 `bitnami/postgresql:latest` 标签修改为 `crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com/gitlab/postgresql:latest` 。
          docker push crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com/gitlab/postgresql:latest将镜像推送到 crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com/gitlab/postgresql:latest 。

      - name: Pull and push bitnami/redis- 名称：拉取和推送 bitnami/redis
        run: |   运行:|
          docker pull bitnami/redis:latest从 Docker Hub 拉取最新版的 Bitnami Redis 镜像。
          docker tag bitnami/redis:latest crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com/gitlab/redis:latest将镜像 `bitnami/redis:latest` 标签修改为 `crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com/gitlab/redis:latest` 。
          docker push crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com/gitlab/redis:latest

      - name: Pull and push gitlab-ce
        run: |   运行:|
          docker pull gitlab/gitlab-ce:latest
          docker tag gitlab/gitlab-ce:latest crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com/gitlab/gitlab-ce:latest
          docker push crpi-aux7x4ompgkgj165.cn-heyuan.personal.cr.aliyuncs.com/gitlab/gitlab-ce:latest
